import {createMission,DELIVERY_DISTANCE} from './dogfight.js';
import * as THREE from 'three';
import RAPIER from '@dimforge/rapier3d-compat';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import nebulaURL from './assets/nebula.png';
import {buildShip,asteroidGeometry} from './drift-models.js';
import {driftForce,pursuitPose,flightHeading} from './drift-flight.js';
const $=id=>document.getElementById(id),canvas=$('space');
const keys=new Set(),mouse=new THREE.Vector2(),rocks=[],dust=[];
let mission;const aim=new THREE.Vector2();let pointerFiring=false;let burstTime=0;
let renderer,scene,camera,composer,bloom,world,body,collider,events,ship,sky,trailGeometry;
let throttle=155;
let state='loading',clock=0,hull=100,charge=100,immunity=0,near=0,distance=0,boosting=false,msgTime=0,sound=true;
const pos=new THREE.Vector3(),vel=new THREE.Vector3(),cameraTarget=new THREE.Vector3(),look=new THREE.Vector3();
let audio,engineOsc,engineGain,wind,windGain;
try{sound=localStorage.getItem('drift-sound')!=='false';}catch(_){}
function audioStart(){if(!sound)return;try{if(!audio){audio=new(window.AudioContext||window.webkitAudioContext)();engineOsc=audio.createOscillator();engineOsc.type='triangle';engineGain=audio.createGain();engineGain.gain.value=0;engineOsc.connect(engineGain);engineGain.connect(audio.destination);engineOsc.start();const buffer=audio.createBuffer(1,audio.sampleRate*2,audio.sampleRate);const data=buffer.getChannelData(0);let low=0;for(let i=0;i<data.length;i++){low=(low+(Math.random()*2-1)*.025)/1.025;data[i]=low*3;}wind=audio.createBufferSource();wind.buffer=buffer;wind.loop=true;windGain=audio.createGain();windGain.gain.value=0;wind.connect(windGain);windGain.connect(audio.destination);wind.start();}if(audio.state==='suspended')audio.resume().catch(()=>{});}catch(_){}}
function audioTick(){if(!audio)return;const active=sound&&state==='playing';engineOsc.frequency.setTargetAtTime(36+vel.length()*.15+(boosting?10:0),audio.currentTime,.15);engineGain.gain.setTargetAtTime(active?.028:0,audio.currentTime,.12);windGain.gain.setTargetAtTime(active?(boosting?.18:.1):0,audio.currentTime,.12);}
function tone(freq,end,duration=.2){if(!sound||audio?.state!=='running')return;const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(end,audio.currentTime+duration);g.gain.setValueAtTime(.0001,audio.currentTime);g.gain.linearRampToValueAtTime(.07,audio.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration+.01);o.onended=()=>{o.disconnect();g.disconnect();};}
function explosion(strength=1){if(!sound||audio?.state!=='running')return;const duration=.8,buffer=audio.createBuffer(1,Math.ceil(audio.sampleRate*duration),audio.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.exp(-i/data.length*7);const source=audio.createBufferSource(),filter=audio.createBiquadFilter(),gain=audio.createGain();source.buffer=buffer;filter.type='lowpass';filter.frequency.setValueAtTime(1700,audio.currentTime);filter.frequency.exponentialRampToValueAtTime(80,audio.currentTime+duration);gain.gain.value=.35*strength;source.connect(filter);filter.connect(gain);gain.connect(audio.destination);source.start();source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect();};tone(80,24,.45);}
function message(text){$('message').textContent=text;msgTime=3;}
const rng=()=>Math.random();
function placeRock(rock,index,initial=false){const z=pos.z-(initial?(index<4?45+index*40:130+index*29):2200+rng()*600);const r=rock.radius;
let x=pos.x+(rng()-.5)*500,y=pos.y+(rng()-.5)*300;
if(initial&&index<14&&Math.hypot(x-pos.x,y-pos.y)<r+20)x=pos.x+(x>=pos.x?1:-1)*(r+25);
rock.mesh.position.set(x,y,z);rock.mesh.rotation.set(rng()*6,rng()*6,rng()*6);rock.mesh.updateMatrixWorld();rock.collider.setTranslation(rock.mesh.position);rock.hit=false;rock.passed=false;
}
async function environment(){scene.background=new THREE.Color(0x040915);scene.add(new THREE.HemisphereLight(0x99c3e9,0x211628,.55));const sun=new THREE.DirectionalLight(0xffddb7,2.5);sun.position.set(-200,180,100);scene.add(sun);const rim=new THREE.DirectionalLight(0x598bff,1.2);rim.position.set(140,-40,-120);scene.add(rim);
const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();scene.environment=pmrem.fromScene(room,.04).texture;scene.environmentIntensity=.45;room.dispose();pmrem.dispose();
const texture=await new THREE.TextureLoader().loadAsync(nebulaURL);texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=renderer.capabilities.getMaxAnisotropy();
// Present the full image behind the flight instead of magnifying a small slice of a sphere.
sky=new THREE.Mesh(new THREE.PlaneGeometry(1,1),new THREE.MeshBasicMaterial({map:texture,depthWrite:false,toneMapped:false}));sky.renderOrder=-2;scene.add(sky);
const stars=[];for(let i=0;i<1600;i++)stars.push((rng()-.5)*11000,(rng()-.5)*7000,-4500-rng()*500);
const starGeo=new THREE.BufferGeometry();starGeo.setAttribute('position',new THREE.Float32BufferAttribute(stars,3));const starField=new THREE.Points(starGeo,new THREE.PointsMaterial({color:0xd0e7ff,size:1.3,sizeAttenuation:false,transparent:true,opacity:.7,depthWrite:false}));starField.name='distantStars';scene.add(starField);
// Fine foreground motes provide depth and short streaks at boost speed.
const positions=new Float32Array(360*6);trailGeometry=new THREE.BufferGeometry();trailGeometry.setAttribute('position',new THREE.BufferAttribute(positions,3));const lines=new THREE.LineSegments(trailGeometry,new THREE.LineBasicMaterial({color:0x92c5ef,transparent:true,opacity:.65,depthWrite:false}));lines.frustumCulled=false;scene.add(lines);for(let i=0;i<360;i++)dust.push({x:(rng()-.5)*140,y:(rng()-.5)*100,z:-rng()*450});
}
function launch(){if(!body)return;mission.reset();burstTime=0;throttle=155;pointerFiring=false;aim.set(0,0);$('resume').hidden=true;state='playing';clock=0;hull=100;charge=100;immunity=0;near=0;distance=0;pos.set(0,0,0);vel.set(0,0,-155);body.setTranslation(pos,true);body.setLinvel(vel,true);body.resetForces(true);keys.clear();mouse.set(0,0);rocks.forEach((r,i)=>placeRock(r,i,true));ship.root.position.copy(pos);ship.root.rotation.set(0,0,0);const pose=pursuitPose(pos,vel,false);camera.position.copy(pose.camera);cameraTarget.copy(pose.target);$('menu').hidden=true;$('pause').disabled=false;$('pause').textContent='PAUSE · P';audioStart();message('Up accelerates. Down slows. Chase the Razorwing and dodge its rear lasers.');canvas.focus();}
function pause(){burstTime=0;pointerFiring=false;if(state==='paused'){state='playing';$('menu').hidden=true;$('pause').textContent='PAUSE · P';canvas.focus();audioStart();}else if(state==='playing'){state='paused';keys.clear();mouse.set(0,0);$('menu').hidden=false;$('resume').hidden=false;$('description').textContent='Flight paused. Resume to continue your current path.';$('pause').textContent='RESUME · P';}audioTick();}
function impact(){if(immunity>0||state!=='playing')return;if($('scenic').checked){immunity=1;return;}hull=Math.max(0,hull-25);immunity=2;tone(110,25,.35);message('Hull impact. Stabilize and steer clear.');if(hull===0){state='ended';keys.clear();$('menu').hidden=false;$('resume').hidden=true;$('description').textContent=`Flight ended. ${(distance/1000).toFixed(1)} km travelled, Dogfight lost. Try again or enable Practice Mode.`;$('pause').disabled=true;audioTick();}}
function tick(dt){if(state!=='playing')return;clock+=dt;immunity=Math.max(0,immunity-dt);msgTime=Math.max(0,msgTime-dt);boosting=keys.has('shift')&&charge>0;charge=THREE.MathUtils.clamp(charge+(boosting?-27:16)*dt,0,100);
const input={x:THREE.MathUtils.clamp((keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),-1,1),y:THREE.MathUtils.clamp((keys.has('w')?1:0)-(keys.has('s')?1:0),-1,1)};
throttle=THREE.MathUtils.clamp(throttle+((keys.has('arrowup')?1:0)-(keys.has('arrowdown')?1:0))*90*dt,0,330);const v=body.linvel();const force=driftForce(v,input,boosting);force.z=(-(throttle+(boosting?70:0))-v.z)*2.5;body.resetForces(true);body.addForce(force,true);world.step(events);events.drainCollisionEvents((a,b,started)=>{if(started&&(a===collider.handle||b===collider.handle))impact();});pos.copy(body.translation());vel.copy(body.linvel());distance=Math.max(distance,-pos.z);
ship.root.position.copy(pos);ship.root.rotation.z=THREE.MathUtils.damp(ship.root.rotation.z,-input.x*.48-vel.x*.002,4,dt);ship.root.rotation.x=THREE.MathUtils.damp(ship.root.rotation.x,input.y*.14,3,dt);ship.root.rotation.y=THREE.MathUtils.damp(ship.root.rotation.y,-vel.x*.002,3,dt);
for(const rock of rocks){rock.mesh.rotation.y+=rock.spin*dt;const d=rock.mesh.position.distanceTo(pos);rock.mesh.geometry=d<280?rock.detail:rock.distant;if(!rock.passed&&rock.mesh.position.z>pos.z+rock.radius+6){rock.passed=true;if(d<rock.radius+28&&!rock.hit){near++;tone(550,850,.12);message('Close pass. Nicely flown.');}}if(d<rock.radius+3)rock.hit=true;if(rock.mesh.position.z>pos.z+75||Math.abs(rock.mesh.position.x-pos.x)>700||Math.abs(rock.mesh.position.y-pos.y)>500)placeRock(rock,0);}
const array=trailGeometry.attributes.position.array;for(let i=0;i<dust.length;i++){const p=dust[i];p.x-=vel.x*dt;p.y-=vel.y*dt;p.z+=-vel.z*dt;if(p.z>30||Math.abs(p.x)>110||Math.abs(p.y)>85){p.z=-450;p.x=(rng()-.5)*180;p.y=(rng()-.5)*120;}array.set([pos.x+p.x,pos.y+p.y,pos.z+p.z,pos.x+p.x-vel.x*.035,pos.y+p.y-vel.y*.035,pos.z+p.z-vel.z*.035],i*6);}trailGeometry.attributes.position.needsUpdate=true;
if(state==='playing'){mission.update(dt,{pos,velocity:vel,distance,camera,aim,firing:burstTime>0||pointerFiring||keys.has(' '),rocks});burstTime=Math.max(0,burstTime-dt);audioTick();}
}
function textureAspect(){const image=sky.material.map.image;return image.width/image.height;}
function draw(dt){if(!ship)return;
const pose=pursuitPose(pos,vel,boosting);camera.position.lerp(pose.camera,1-Math.exp(-dt*6));camera.position.z=pose.camera.z;cameraTarget.lerp(pose.target,1-Math.exp(-dt*7));cameraTarget.z=pose.target.z;camera.lookAt(cameraTarget);camera.rotateZ(ship.root.rotation.z*.08);camera.fov=THREE.MathUtils.damp(camera.fov,boosting?72:64,3,dt);camera.updateProjectionMatrix();sky.quaternion.copy(camera.quaternion);sky.position.copy(camera.position).add(new THREE.Vector3(0,0,-6000).applyQuaternion(camera.quaternion));const skyHeight=2*6000*Math.tan(THREE.MathUtils.degToRad(camera.fov/2));const skyAspect=textureAspect();sky.scale.set(Math.max(skyHeight*camera.aspect,skyHeight*skyAspect),Math.max(skyHeight,skyHeight*camera.aspect/skyAspect),1);scene.getObjectByName('distantStars').position.copy(pos);
for(const e of ship.engines){const length=boosting?8.5:4.8;e.flame.scale.y=length/4.8;e.flame.position.z=e.z+length/2;e.material.uniforms.uTime.value=clock;e.material.uniforms.uBoost.value=boosting?1:0;}
camera.updateMatrixWorld();
const direction=vel.lengthSq()>1?vel.clone().normalize():new THREE.Vector3(0,0,-1);
const flightPoint=pos.clone().addScaledVector(direction,400).project(camera);
const marker=$('flightpath');marker.style.left=(50+flightPoint.x*50)+'%';marker.style.top=(50-flightPoint.y*50)+'%';
const heading=flightHeading(vel);$('heading').textContent=`TRACK ${heading.yaw>=0?'R':'L'} ${Math.abs(heading.yaw).toFixed(0)}° | ${heading.pitch>=0?'CLIMB':'DIVE'} ${Math.abs(heading.pitch).toFixed(0)}°`;
$('position').textContent=`LATERAL ${pos.x.toFixed(0)} m | ALTITUDE ${pos.y.toFixed(0)} m`;
const ms=mission.status;const targetMarker=$('targetmarker');targetMarker.hidden=!ms.target||state!=='playing';if(ms.target){const screen=ms.target.clone().project(camera);targetMarker.style.left=THREE.MathUtils.clamp(50+screen.x*50,6,94)+'%';targetMarker.style.top=THREE.MathUtils.clamp(50-screen.y*50,18,80)+'%';targetMarker.textContent='[ RAZORWING '+Math.round(ms.enemyHull/18*100)+'% ]';}
$('objective').textContent='RAZORWING HULL '+Math.round(ms.enemyHull/18*100)+'% | SET SPEED '+Math.round(throttle)+' M/S';$('heat').value=ms.heat;$('heatlabel').textContent=ms.locked?'COOLING':'CANNONS';
$('velocity').textContent=Math.round(vel.length());$('distance').textContent=(distance/1000).toFixed(1);$('hull').value=hull;$('hull-text').textContent=hull;$('charge').value=charge;$('near').textContent=ms.target?'TARGET '+Math.round(ms.target.distanceTo(pos))+' M':'';$('flash').style.opacity=immunity>0&&!$('scenic').checked?Math.max(0,immunity-1.5)*.75:0;if(msgTime===0&&state==='playing')$('message').textContent='';
if($('quality').value==='low')renderer.render(scene,camera);else composer.render();
}
function resize(){if(!renderer)return;const mode=$('quality').value,ratio=mode==='high'?Math.min(devicePixelRatio,1.75):mode==='low'?1:Math.min(devicePixelRatio,1.25);renderer.setPixelRatio(ratio);renderer.setSize(innerWidth,innerHeight);composer.setPixelRatio(ratio);composer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}
async function boot(){try{await RAPIER.init();world=new RAPIER.World({x:0,y:0,z:0});world.timestep=1/120;events=new RAPIER.EventQueue(true);scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(64,innerWidth/innerHeight,.1,7000);renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));bloom=new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.65,.4,1.05);composer.addPass(bloom);composer.addPass(new OutputPass());
await environment();mission=createMission(scene,{message,tone,explosion,damage:impact,destroyRock:rock=>placeRock(rock,0),complete:kills=>{if(state!=='playing')return;state='won';keys.clear();pointerFiring=false;$('menu').hidden=false;$('resume').hidden=true;$('pause').disabled=true;$('description').textContent=`Dogfight won. Razorwing destroyed. ${Math.round(hull)}% hull remaining.${$('scenic').checked?' Scenic Mode flight.':''}`;tone(440,880,.6);audioTick();}});ship=buildShip();scene.add(ship.root);body=world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setCcdEnabled(true).lockRotations().setLinearDamping(.01));collider=world.createCollider(RAPIER.ColliderDesc.ball(1.7).setMass(1).setRestitution(.12).setActiveEvents(RAPIER.ActiveEvents.COLLISION_EVENTS),body);camera.position.set(0,5.1,23);cameraTarget.set(0,1.2,-55);resize();state='ready';$('launch').disabled=false;$('loading').textContent='FLIGHT READY · ALL ASSETS LOADED LOCALLY';let last=null,acc=0;renderer.setAnimationLoop(now=>{if(last===null)last=now;const dt=Math.min((now-last)/1000,.08);last=now;acc+=dt;while(acc>=1/120){tick(1/120);acc-=1/120;}draw(dt);});}catch(e){$('loading').textContent='Unable to start: '+e.message;console.error(e);}}
$('launch').addEventListener('click',launch);$('resume').addEventListener('click',()=>{if(state==='paused')pause();});$('pause').addEventListener('click',pause);$('quality').addEventListener('change',resize);$('sound').textContent=sound?'AUDIO ON':'AUDIO OFF';$('sound').addEventListener('click',()=>{sound=!sound;try{localStorage.setItem('drift-sound',String(sound));}catch(_){}$('sound').textContent=sound?'AUDIO ON':'AUDIO OFF';audioStart();audioTick();});window.addEventListener('resize',resize);
window.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.target.closest('input,select,button'))return;const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','shift','p','r',' '].includes(k))e.preventDefault();if(k==='p'&&!e.repeat)pause();else if(k==='r'&&!e.repeat&&body)launch();else if(state==='playing')keys.add(k);});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();aim.set((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2);mouse.set(THREE.MathUtils.clamp((e.clientX-r.left)/r.width*2-1,-1,1),THREE.MathUtils.clamp(1-(e.clientY-r.top)/r.height*2,-1,1));});canvas.addEventListener('pointerdown',e=>{if(e.button===0&&state==='playing'){pointerFiring=true;canvas.focus();}});window.addEventListener('pointerup',()=>pointerFiring=false);canvas.addEventListener('pointerleave',()=>{mouse.set(0,0);aim.set(0,0);pointerFiring=false;});for(const b of document.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(state==='playing')keys.add(b.dataset.key);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys.delete(b.dataset.key));}window.addEventListener('blur',()=>{if(state==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause();});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();if(state==='playing')pause();$('loading').textContent='Graphics context lost. Reload to restart.';});boot();

canvas.addEventListener('dblclick',e=>{e.preventDefault();if(state!=='playing')return;const r=canvas.getBoundingClientRect();aim.set((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2);burstTime=.3;canvas.focus();audioStart();});
